server:
  port: 8081
spring:
    datasource:
      username: root
      password: MaJian880926
      url: jdbc:mysql://192.168.80.218:3306/ztsmartcard
      driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#    configuration:
#      map-underscore-to-camel-case: false
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl