server:
  port: 8085
spring:
    datasource:
      username: root
      password: root
      url: jdbc:mysql://192.168.80.216:3306/ztsmartcard
      driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#    configuration:
#      map-underscore-to-camel-case: false
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
waterProperties:
  #服务器远程校验sn合法url
  device-Validity-Url: http://192.168.80.222:6800/api/AuthorizeDevice/AuthorizeDevice